import type { User, Shop, Product, Order } from "./types"

export const DEMO_USERS: User[] = [
  {
    id: "demo-customer-1",
    phone: "+91 98765 43210",
    role: "customer",
    name: "Demo Customer",
    createdAt: new Date().toISOString(),
  },
  {
    id: "demo-owner-1",
    phone: "+91 98765 43211",
    role: "owner",
    name: "Demo Shop Owner",
    createdAt: new Date().toISOString(),
  },
]

export const DEMO_SHOPS: Shop[] = [
  {
    id: "shop-1",
    ownerId: "demo-owner-1",
    name: "Fresh Mart Grocery",
    category: "Grocery",
    description: "Your one-stop shop for fresh groceries, fruits, vegetables, and daily essentials. Quality products at best prices.",
    lat: 12.9716,
    lng: 77.5946,
    address: "42 MG Road, Bangalore 560001",
    upiId: "freshmart@upi",
    openTime: "08:00",
    closeTime: "21:00",
    workingDays: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    isTemporarilyClosed: false,
    isSetupComplete: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "shop-2",
    ownerId: "demo-owner-1",
    name: "Spice Kitchen",
    category: "Restaurant",
    description: "Authentic Indian cuisine prepared with love. Biryanis, curries, and street food favorites available for quick pickup.",
    lat: 12.9750,
    lng: 77.5980,
    address: "15 Brigade Road, Bangalore 560025",
    upiId: "spicekitchen@upi",
    openTime: "10:00",
    closeTime: "22:00",
    workingDays: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    isTemporarilyClosed: false,
    isSetupComplete: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "shop-3",
    ownerId: "demo-owner-1",
    name: "Daily Bakery",
    category: "Bakery",
    description: "Freshly baked bread, pastries, cakes, and cookies every morning. Perfect for breakfast and evening snacks.",
    lat: 12.9680,
    lng: 77.5910,
    address: "8 Church Street, Bangalore 560001",
    upiId: "dailybakery@upi",
    openTime: "06:00",
    closeTime: "20:00",
    workingDays: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
    isTemporarilyClosed: false,
    isSetupComplete: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "shop-4",
    ownerId: "demo-owner-1",
    name: "MedPlus Pharmacy",
    category: "Pharmacy",
    description: "All types of medicines, health supplements, and wellness products. Prescription and OTC medicines available.",
    lat: 12.9730,
    lng: 77.5960,
    address: "22 Residency Road, Bangalore 560025",
    upiId: "medplus@upi",
    openTime: "07:00",
    closeTime: "23:00",
    workingDays: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
    isTemporarilyClosed: false,
    isSetupComplete: true,
    createdAt: new Date().toISOString(),
  },
]

export const DEMO_PRODUCTS: Product[] = [
  // Fresh Mart Grocery
  { id: "prod-1", shopId: "shop-1", name: "Basmati Rice (5kg)", description: "Premium aged basmati rice", price: 450, category: "Food & Beverages", inStock: true, createdAt: new Date().toISOString() },
  { id: "prod-2", shopId: "shop-1", name: "Organic Milk (1L)", description: "Farm-fresh organic milk", price: 65, category: "Dairy", inStock: true, createdAt: new Date().toISOString() },
  { id: "prod-3", shopId: "shop-1", name: "Fresh Tomatoes (1kg)", description: "Locally sourced ripe tomatoes", price: 40, category: "Fresh Produce", inStock: true, createdAt: new Date().toISOString() },
  { id: "prod-4", shopId: "shop-1", name: "Whole Wheat Bread", description: "Freshly baked whole wheat bread", price: 45, category: "Bakery", inStock: true, createdAt: new Date().toISOString() },
  { id: "prod-5", shopId: "shop-1", name: "Eggs (12 pack)", description: "Free-range farm eggs", price: 85, category: "Dairy", inStock: true, createdAt: new Date().toISOString() },
  { id: "prod-6", shopId: "shop-1", name: "Cooking Oil (1L)", description: "Refined sunflower oil", price: 150, category: "Food & Beverages", inStock: true, createdAt: new Date().toISOString() },
  // Spice Kitchen
  { id: "prod-7", shopId: "shop-2", name: "Chicken Biryani", description: "Hyderabadi style dum biryani with raita", price: 280, category: "Food & Beverages", inStock: true, createdAt: new Date().toISOString() },
  { id: "prod-8", shopId: "shop-2", name: "Paneer Butter Masala", description: "Rich and creamy paneer curry", price: 220, category: "Food & Beverages", inStock: true, createdAt: new Date().toISOString() },
  { id: "prod-9", shopId: "shop-2", name: "Masala Dosa", description: "Crispy dosa with potato filling and chutneys", price: 120, category: "Food & Beverages", inStock: true, createdAt: new Date().toISOString() },
  { id: "prod-10", shopId: "shop-2", name: "Veg Fried Rice", description: "Indo-Chinese style vegetable fried rice", price: 180, category: "Food & Beverages", inStock: true, createdAt: new Date().toISOString() },
  { id: "prod-11", shopId: "shop-2", name: "Gulab Jamun (4pc)", description: "Soft and sweet gulab jamun dessert", price: 100, category: "Food & Beverages", inStock: true, createdAt: new Date().toISOString() },
  // Daily Bakery
  { id: "prod-12", shopId: "shop-3", name: "Chocolate Cake (500g)", description: "Rich chocolate truffle cake", price: 450, category: "Bakery", inStock: true, createdAt: new Date().toISOString() },
  { id: "prod-13", shopId: "shop-3", name: "Croissant (2pc)", description: "Buttery flaky croissants", price: 120, category: "Bakery", inStock: true, createdAt: new Date().toISOString() },
  { id: "prod-14", shopId: "shop-3", name: "Sourdough Bread", description: "Artisan sourdough loaf", price: 180, category: "Bakery", inStock: true, createdAt: new Date().toISOString() },
  { id: "prod-15", shopId: "shop-3", name: "Blueberry Muffin", description: "Freshly baked blueberry muffin", price: 80, category: "Bakery", inStock: true, createdAt: new Date().toISOString() },
  { id: "prod-16", shopId: "shop-3", name: "Cookie Box (6pc)", description: "Assorted cookies gift box", price: 250, category: "Bakery", inStock: true, createdAt: new Date().toISOString() },
  // MedPlus Pharmacy
  { id: "prod-17", shopId: "shop-4", name: "Paracetamol (10 tabs)", description: "For fever and pain relief", price: 25, category: "Personal Care", inStock: true, createdAt: new Date().toISOString() },
  { id: "prod-18", shopId: "shop-4", name: "Vitamin C (30 tabs)", description: "Daily vitamin C supplement", price: 180, category: "Personal Care", inStock: true, createdAt: new Date().toISOString() },
  { id: "prod-19", shopId: "shop-4", name: "Hand Sanitizer (200ml)", description: "Alcohol-based hand sanitizer", price: 95, category: "Personal Care", inStock: true, createdAt: new Date().toISOString() },
  { id: "prod-20", shopId: "shop-4", name: "First Aid Kit", description: "Complete first aid kit for home", price: 350, category: "Household", inStock: true, createdAt: new Date().toISOString() },
  { id: "prod-21", shopId: "shop-4", name: "Face Masks (10pc)", description: "3-ply disposable face masks", price: 120, category: "Personal Care", inStock: true, createdAt: new Date().toISOString() },
]

export const DEMO_ORDERS: Order[] = [
  {
    id: "ORD-20260208-001",
    customerId: "demo-customer-1",
    shopId: "shop-1",
    shopName: "Fresh Mart Grocery",
    items: [
      { productId: "prod-1", productName: "Basmati Rice (5kg)", price: 450, quantity: 1 },
      { productId: "prod-2", productName: "Organic Milk (1L)", price: 65, quantity: 2 },
    ],
    total: 580,
    status: "completed",
    pickupCode: "4821",
    colorCode: "#6366F1",
    colorLabel: "Indigo",
    qrData: "SF-ORD-20260208-001-shop-1-completed-6366F1",
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 82800000).toISOString(),
  },
  {
    id: "ORD-20260208-002",
    customerId: "demo-customer-1",
    shopId: "shop-2",
    shopName: "Spice Kitchen",
    items: [
      { productId: "prod-7", productName: "Chicken Biryani", price: 280, quantity: 2 },
      { productId: "prod-11", productName: "Gulab Jamun (4pc)", price: 100, quantity: 1 },
    ],
    total: 660,
    status: "ready",
    pickupCode: "7359",
    colorCode: "#10B981",
    colorLabel: "Green",
    qrData: "SF-ORD-20260208-002-shop-2-ready-10B981",
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 1800000).toISOString(),
  },
]
